### ISSUE TITLE
some se

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#15]
1. It would be nice to change the url "/dataset/words?pattern=" to  "/dataset/words?q="

2. The angular needs a JSON result, I suggest this format:

```
{
  "total_count": 10,
  "items": [
    {
      "name": "homogenized"
      },
    {
      "name": "homocysteine"
      }
    ...
    ]
}
```

**Comment by baimingze** [comment]
@ypriverol

**Comment by ypriverol** [comment]
@baimingze I will do it!!
