### ISSUE TITLE
the algorithm for annotation

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#19]
#### 1.  get annotation info of a word
```
http://data.bioontology.org/annotator?text=modifications&longest_only=true&whole_word_only=false
```
#### 2.   get the first matched_word ("MODIFICATION") from annotation info (excludes the word not from first char, such as FICATION)
```
"annotations": [
{
    "from": 1,
    "to": 12,
    "matchType": "SYN",
    "text": "MODIFICATION"

}
```
#### 3.   deal the urls which comes from bioontology.org and the match is as same as the matched_word in step 2, to get the detail infos(Accession, ontology)
```
"@id": "http://purl.bioontology.org/ontology/HL7/C1554963",
"@id": "http://purl.bioontology.org/ontology/LNC/LA11133-8",

```

### results(only with two ontologies: MESH and MS)
synonyms are in the square brackets
```
samples
['sample']
study
analysis
['analysis', 'chemical analysis', 'assay', 'determination']
sequencing
genome
['genome', 'genomes']
cell
['cell']
human
['human', 'homo sapiens', 'man (taxonomy)', 'man, modern', 'modern man']
performed
cancer
['cancer', 'benign neoplasms', 'tumors', 'neoplasm', 'benign neoplasm', 'cancers', 'neoplasm, benign', 'neoplasms, benign', 'neoplasia', 'tumor']
high
['high']
mass
ms
whole
exome
['exome', 'exomes']
dna
['dna', 'dna, double stranded', 'ds-dna', 'double-stranded dna', 'deoxyribonucleic acids', 'deoxyribonucleic acid', 'ds dna', 'dna, double-stranded']
patients
['patients', 'client', 'clients', 'patient']
disease
['disease', 'diseases']
genes
['genes', 'genetic materials', 'cistrons', 'materials, genetic', 'cistron', 'genetic material', 'material, genetic', 'gene']
genetic
['gene', 'genetic materials', 'cistrons', 'materials, genetic', 'cistron', 'genetic material', 'material, genetic']
used
['use']
identified
mutations
['mutations']
identify
proteome
['proteome', 'proteomes']
cells
['cells', 'cell']
project
wide
['wide']
sample
['sample']
part
gene
['gene', 'genetic materials', 'cistrons', 'materials, genetic', 'cistron', 'genetic material', 'material, genetic']
genomic
spectrometry
['spectrometry', 'analysis, spectrum', 'spectroscopy']
including
individuals
http
based
cases
cohort
lc
associated

```

**Comment by baimingze** [comment]
### annotated words
```
these words have no annotation info
['study', 'sequencing', 'performed', 'mass', 'ms', 'whole', 'identified', 'identify', 'project', 'part', 'genomic', 'including', 'individuals', 'http', 'based', 'cases', 'cohort', 'lc']
```
--------------------------
```
{'mergedWords': ['samples', 'sample'], 'label': 'sample', 'frequent': '1320', 'No': '0'}
{'mergedWords': ['analysis'], 'label': 'analysis', 'frequent': '950', 'No': '1'}
{'mergedWords': ['genome'], 'label': 'genome', 'frequent': '828', 'No': '2'}
{'mergedWords': ['cell'], 'label': 'cell', 'frequent': '1004', 'No': '3'}
{'mergedWords': ['human'], 'label': 'human', 'frequent': '642', 'No': '4'}
{'mergedWords': ['cancer'], 'label': 'cancer', 'frequent': '545', 'No': '5'}
{'mergedWords': ['high'], 'label': 'high', 'frequent': '497', 'No': '6'}
{'mergedWords': ['exome'], 'label': 'exome', 'frequent': '455', 'No': '7'}
{'mergedWords': ['dna'], 'label': 'dna', 'frequent': '446', 'No': '8'}
{'mergedWords': ['patients'], 'label': 'patients', 'frequent': '427', 'No': '9'}
{'mergedWords': ['disease'], 'label': 'disease', 'frequent': '414', 'No': '10'}
{'mergedWords': ['genes', 'gene', 'genetic'], 'label': 'gene', 'frequent': '1119', 'No': '11'}
{'mergedWords': ['used'], 'label': 'used', 'frequent': '373', 'No': '13'}
{'mergedWords': ['mutations'], 'label': 'mutations', 'frequent': '364', 'No': '14'}
{'mergedWords': ['proteome'], 'label': 'proteome', 'frequent': '336', 'No': '15'}
{'mergedWords': ['wide'], 'label': 'wide', 'frequent': '320', 'No': '16'}
{'mergedWords': ['spectrometry'], 'label': 'spectrometry', 'frequent': '287', 'No': '17'}
{'mergedWords': ['associated'], 'label': 'associated', 'frequent': '269', 'No': '18'}
```

**Comment by ypriverol** [comment]
@baimingze this work is fantastic my friend, well done. How are you planning to store this information?, As far as I see we have two options:
  - As we discuss before we should do it in the mongoDB database. The java library will allow you to 
    handle the database for inserts, updates and retrieve options. You can try with it, but is really simple.  
  - We can use these words during the annotation process and put the synonyms into the XML file, it will 
    allow us to search by them, but also work in the similarity score and other metrics using this 
    annotations. 
 My opinion is that this information should be in the XML for two main reasons: 
     (i) We can search by sysnomyms given an incredible power to the search and for the same time been 
         able to search not only but what is complete write in the text. 
     (ii) We will not change the frequently words part of the web-services because the words will be in the 
          XML-files.  
 Apart of the MS and MESH ontologies we should explore other important ontologies such as:     
    - Experimental Factor Ontology - EFO 
    - Tissue BRENDA ontology 
    - GO (Gene ontology)
 
@baimingze we can discuss this issues on thursday.

**Comment by baimingze** [comment]
### So far, only from EFO can get annotation info

1. example detail info in EFO : http://www.ebi.ac.uk/efo/EFO_0000244
2. TBO:   404 error at"http://data.bioontology.org/ontologies/BTO/classes/BTO_0000759", which is get from "data.bioontology.org/annotator?ontologies=BTO&text=liver"
3. GO: got empty list from "http://data.bioontology.org/annotator?ontologies=GO&text=gene"
