### ISSUE TITLE
mockup of annotation

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#20]
![mockup of annotation](https://cloud.githubusercontent.com/assets/3970400/8745680/33b09b98-2c7a-11e5-9b4f-846eb5547020.png)

![flowchart of annotation](https://cloud.githubusercontent.com/assets/3970400/8745712/7355b8fa-2c7a-11e5-9a07-47385765c54c.png)

**Comment by baimingze** [comment]
### choose the longest word for overlapped
we got these words now(in Python)
```
[{'to': 24, 'from': 12, 'text': 'rhesus monkey'}, {'to': 62, 'from': 58, 'text': 'human'}, {'to': 70, 'from': 64, 'text': 'primate'}, {'to': 84, 'from': 72, 'text': 'animal models'}, {'to': 102, 'from': 98, 'text': 'human'}, {'to': 111, 'from': 104, 'text': 'diseases'}, {'to': 193, 'from': 188, 'text': 'humans'}, {'to': 213, 'from': 206, 'text': 'research'}, {'to': 234, 'from': 221, 'text': 'rhesus monkeys'}, {'to': 316, 'from': 292, 'text': 'protein sequence database'}, {'to': 417, 'from': 411, 'text': 'tissues'}, {'to': 530, 'from': 526, 'text': 'human'}, {'to': 539, 'from': 532, 'text': 'database'}, {'to': 629, 'from': 622, 'text': 'proteins'}, {'to': 709, 'from': 704, 'text': 'future'}, {'to': 723, 'from': 711, 'text': 'rhesus monkey'}, {'to': 732, 'from': 725, 'text': 'proteome'}, {'to': 741, 'from': 734, 'text': 'research'}, {'to': 142, 'from': 139, 'text': 'size'}, {'to': 331, 'from': 322, 'text': 'sufficient'}, {'to': 403, 'from': 396, 'text': 'multiple'}, {'to': 425, 'from': 422, 'text': 'male'}, {'to': 439, 'from': 434, 'text': 'female'}, {'to': 476, 'from': 473, 'text': 'high'}, {'to': 669, 'from': 666, 'text': 'male'}, {'to': 680, 'from': 675, 'text': 'female'}]
```
for 
```
"Though the rhesus monkey is one of the most valuable non-human primate animal models for various human diseases because of its manageable size and genetic and proteomic similarities with humans, proteomic research using rhesus monkeys still remains challenging due to the lack of a complete protein sequence database and sufficient proteomic information. In this project, proteomic profiling of multiple organ tissues, 9 male and 11 female were performed in an automated, high-throughput manner employing annotated UniProtKB human database. Based on the success of this alternative interpretation of MS data, the list of proteins identified from total 12 organs of male and female subjects will benefit future rhesus monkey proteome research."
```

**Comment by ypriverol** [comment]
- [ ] The main component of the annotation is the Annotator Lib. It will have two main dependencies the
    Biontology annotation library and the already implemented mongo db. 
- [ ] The synonyms indexing component will take (weekly based) the new datasets and annotated the 
   enrichment in the MongoDB database.  
     - [ ] For every database check the new datasets (using the mongo db you can trace the datasets) for 
          every dataset you should create a set of fields and for each field the synonyms. 
- [ ] Implement the functionality in the annotator lib to retrieve for an specific field and dataset the 
   annotations and synonyms, then the EBI developers will be able to use this functions to do the 
   enrichment during indexing.  

![annotator-pipeline](https://cloud.githubusercontent.com/assets/52113/8957875/4c88c0c2-35f9-11e5-919b-d6596e5f93fe.png)

**Comment by ypriverol** [comment]
I will close this issue with a new pipeline we will work on this issue and this is not part of the web-service.
