### ISSUE TITLE
Ordering of search result is not working

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#24]
----
On http://www.omicsdi.org/#/search?q=repository:%22ArrayExpress%22%20AND%20omics_type:%22Transcriptomics%22%20AND%20omics_type:%22Genomics%22, clicking on sorting up/down arrows doesn’t seem to change the order of experiments shown (for any of the ‘accession’, ‘Relevance’ or ‘Publication date’ categories)

the sorting is not working any more in webservice
you got same result with different parameters, something may be changed in Ebeye.

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=id&order=ascending&start=0

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=id&order=descending&start=0

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=publication_date&order=descending&start=0

**Comment by ypriverol** [comment]
Problem in the web services. Already fixed.
