### ISSUE TITLE
similarity chord data not right?

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#26]
https://github.com/BD2K-DDI/ddi-web-app/issues/96

please check this url, may be some of the code in web service has changed some thing:
http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/enrichment/getSimilarityInfo?accession=ST000054&database=MetabolomicsWorkbench returns a lot of datasets, and the front end system can draw the right chord.

http://www.omicsdi.org/ws/enrichment/getSimilarityInfo?accession=ST000054&database=MetabolomicsWorkbench returns only two datasets, but it looks not right.

**Comment by ypriverol** [comment]
Bug fixing in the web services.
