### ISSUE TITLE
we need TAXONOMY "id" in the " get /stats/organisms"

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#3]
now the return results is like this:
"[
  {
    "value": "2519",
    "name": "Total"
  },
  {
    "value": "676",
    "name": "Homo sapiens"
  }
]

we need the TAXONOMY "id" added in each object,like this:

[
  {
    "value": "2519",
    "name": "Total"
    "id"      :""
   },
  {
    "value": "676",
    "name": "Homo sapiens"
    "id":"9606"
  }
]

**Comment by ypriverol** [comment]
Close, code committed
