### ISSUE TITLE
no error info to nonexist dataset when getting dataset 

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-service#8]
as this url:
```
http://localhost:9091/dataset/get?acc=PXD001998&database=PRIDE
```

no result, no error response. 

It would be better to return some error info when the dataset is not exist.

**Comment by ypriverol** [comment]
@baimingze I will return an empty object like:

{
id: null,
source: null,
name: null,
description: null,
keywords: null,
organisms: null,
publicationDate: null,
protocols: null,
instruments: null,
experimentType: null,
labMembers: null,
full_dataset_link: null
}

Let me know if you are ok to close this issue.

**Comment by ypriverol** [comment]
done
